---
# - include_tasks: config.yml

- name: Create vth group info.
  group:
    name: '{{ hostname }}'

- name: Create user.
  user:
    name: '{{ hostname }}'
    group: '{{ hostname }}'

- name: Check docker install.
  package:
    name: docker
    state: present


# - include_tasks: setup.yml
# - include_tasks: service.yml


- name: Restart a container
  community.docker.docker_container:
    name: frontend
    image: trongminhjr/webserver:latest
    # image: trongminhjr/devmidterm-web:v1
    # image: webserver
    state: started
    restart_policy: unless-stopped
    # networks: 
    #   - name: "{{NETWORK}}"
    ports:
      - "3000:3000"
    