- name: Run the docker API images
  community.docker.docker_container:
    name: backend
    image: trongminhjr/devmidterm_api:v1
    state: started
    restart_policy: unless-stopped
    # networks: 
    #   - name: "{{ NETWORK}}"
    ports:
      - "80:80"
    env:
      MONGODB_HOST : "172.17.0.1"
    